schema : schema.graphql
extensions :
    endpoints :
        Default GraphQL Endpoint :
            url : http://localhost:8080/demo/graphql
            headers :
                user-agent : JS GraphQL
            introspect : false
